spring:
  application:
    name: els-prom-sync
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  exchange-rate: 44.5
  ai-enabled: true

telegram:
  enabled: true
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

pricing:
  panel-markup: 1.12
  cable-markup: 1.12

  cheap-price-usd: 200
  standard-price-usd: 600
  high-price-usd: 2000
  max-price-usd: 6000

  cheap-markup: 1.35
  standard-markup: 1.15
  min-markup: 1.08

google:
  sheets:
    spreadsheet-id: ${DEALER_SPREADSHEET_ID}

openai:
  api-key: ${OPENAI_API_KEY}
